services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: api_gest_med
    container_name: container_gest_med
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    restart: always

  db:
    image: postgres:16.3
    container_name: container_postgres_gest_med
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      retries: 5
    restart: always

volumes:
  postgres_data:
